const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const uga_invoice_item = require('../schemas/uga_invoice_item');

module.exports = mongoose.model(
    'uga_Invoice',
    new Schema({
        "activities": [String],
        "customAttributes.approvalTimerEnabled": Boolean,
        "customAttributes.approvalTimerStart": Date,
        "approved": Boolean,
        "customAttributes.businessDaysInState": Number,
        "customAttributes.businessManager": String,
        "categories": [String],
        "company": String,
        "components": [String],
        "contacts": [String],
        "containers": [String],
        "createdBy": String,
        "currentSmartFormStartingStep": String,
        "dateActivated": Date,
        "dateArchived": Date,
        "dateCompleted": Date,
        "dateCreated": Date,
        "dateEnteredState": Date,
        "dateExpired": Date,
        "dateModified": Date,
        "description": String,
        "displayInNewWindow": Boolean,
        "documents": [String],
        "editPermissions": [String],
        "ID": String,
        "image": String,
        "majorVersion": Number,
        "metaCloneId": String,
        "metadataDoc": String,
        "minorVersion": Number,
        "modifiers": [String],
        "name": String,
        "notes": String,
        "notesAsStr": String,
        "owner": String,
        "parentProject": String,
        "projects": [String],
        "quickSearchDoc": String,
        "readPermissions": [String],
        "RequiresSearchProxyUpdate": Boolean,
        "resourceContainer": String,
        "reviewerNotes": [String],
        "status": String,
        "type": String,
        "customAttributes.uga_cageCard_set": [String],
        "customAttributes.uga_csv_set": [String],
        "customAttributes.uga_date_calculated": Date,
        "customAttributes.uga_date_piReviewSent": Date,
        "customAttributes.uga_date_vetMedReviewSent": Date,
        "customAttributes.uga_invoice_item_set": [uga_invoice_item],
        "customAttributes.uga_invoiceDate": Date,
        "customAttributes.uga_Month": String,
        "customAttributes.uga_pdf": String,
        "customAttributes.uga_pdf_set": [String],
        "customAttributes.uga_pi": String,
        "customAttributes.uga_Year": String,
        "versionDescription": String
    })
);
