//? Can these two lines be combined?
import * as mongoose from 'mongoose';
import { Schema } from 'mongoose';

const uga_invoice_item = new Schema({
    "dateCreated": Date,
    "dateModified": Date,
    "ID": String,
    "metaCloneId": String,
    "customAttributes.uga_account": String,
    "customAttributes.uga_associatedExports_set": [String],
    "customAttributes.uga_associatedOrderLineItem_set": [String],
    "customAttributes.uga_cageCard_historyItem_set": [String],
    "customAttributes.uga_cageCard_set": [String],
    "customAttributes.uga_charge_date": Date,
    "customAttributes.uga_chargeType": String,
    "customAttributes.uga_chartString_perDiem": String,
    "customAttributes.uga_chartString_procurement": String,
    "customAttributes.uga_chartString_serviceRequest": String,
    "customAttributes.uga_description": String,
    "customAttributes.uga_facility": String,
    "customAttributes.uga_isOtherCharge": Boolean,
    "customAttributes.uga_paymentMethod": String,
    "customAttributes.uga_perDiem": String,
    "customAttributes.uga_profileSelection_perDiem": String,
    "customAttributes.uga_profileSelection_procurement": String,
    "customAttributes.uga_profileSelection_serviceRequest": String,
    "customAttributes.uga_protocol": String,
    "customAttributes.uga_quantity": Number,
    "customAttributes.uga_removedFromSet": Boolean,
    "customAttributes.uga_servicesActivityItem_set": [String],
    "customAttributes.uga_species": String,
    "customAttributes.uga_total": Number,
    "customAttributes.uga_unit_cost": Number
});

module.exports = mongoose.model(
    'uga_Invoice',
    new Schema({
        "activities": [String],
        "customAttributes.approvalTimerEnabled": Boolean,
        "customAttributes.approvalTimerStart": Date,
        "approved": Boolean,
        "customAttributes.businessDaysInState": Number,
        "customAttributes.businessManager": String,
        "categories": [String],
        "company": String,
        "components": [String],
        "contacts": [String],
        "containers": [String],
        "createdBy": String,
        "currentSmartFormStartingStep": String,
        "dateActivated": Date,
        "dateArchived": Date,
        "dateCompleted": Date,
        "dateCreated": Date,
        "dateEnteredState": Date,
        "dateExpired": Date,
        "dateModified": Date,
        "description": String,
        "displayInNewWindow": Boolean,
        "documents": [String],
        "editPermissions": [String],
        "ID": String,
        "image": String,
        "majorVersion": Number,
        "metaCloneId": String,
        "metadataDoc": String,
        "minorVersion": Number,
        "modifiers": [String],
        "name": String,
        "notes": String,
        "notesAsStr": String,
        "owner": String,
        "parentProject": String,
        "projects": [String],
        "quickSearchDoc": String,
        "readPermissions": [String],
        "RequiresSearchProxyUpdate": Boolean,
        "resourceContainer": String,
        "reviewerNotes": [String],
        "status": String,
        "type": String,
        "customAttributes.uga_cageCard_set": [String],
        "customAttributes.uga_csv_set": [String],
        "customAttributes.uga_date_calculated": Date,
        "customAttributes.uga_date_piReviewSent": Date,
        "customAttributes.uga_date_vetMedReviewSent": Date,
        "customAttributes.uga_invoice_item_set": [uga_invoice_item],
        "customAttributes.uga_invoiceDate": Date,
        "customAttributes.uga_Month": String,
        "customAttributes.uga_pdf": String,
        "customAttributes.uga_pdf_set": [String],
        "customAttributes.uga_pi": String,
        "customAttributes.uga_Year": String,
        "versionDescription": String
    })
);
